# FastAPI Dockerfile
FROM python:3.9

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8888

ENV MODEL_NAME="mistral-7b-instruct-v0.1.Q5_K_M.gguf"

CMD ["uvicorn", "fastapi_server:app", "--host", "0.0.0.0", "--port", "8888"]